### PR TITLE
Move to /var/cache/swcatalog

### PR DESCRIPTION
**Pull request by Vogtinator**

### CODE REVIEW

**Comment by Vogtinator** [comment]
Needs patched libappstream-glib: https://build.opensuse.org/request/show/1143439

Ideally there'll be a versioned requires but as it's a patch that's not trivial :-/

**Comment by DimStar77** [comment]
> Ideally there'll be a versioned requires but as it's a patch that's not trivial :-/

```
Provides: patch(swcatalog)
```

and on the other side:

```
Requires: (appstream-glib with patch(swcatalog))
```

(or similar stuff)

**Comment by Vogtinator** [comment]
Yep, nontrivial. Should I resubmit appstream-glib with the provides or is it ok as-is for now?

**Comment by DimStar77** [comment]
as-glib now provides: `asglib(swcatalog)` - so we can use that

**Review by DimStar77 — APPROVED** [review]

**Pull request merged**
